### ISSUE TITLE
Figure out routing

### ISSUE THREAD

**Issue by wreppun** [outlikealambda/trustocracy-elm#1]

**Comment by megesdal** [comment]
Interesting read here: https://github.com/rgrempel/elm-route-hash

**Comment by megesdal** [comment]
https://groups.google.com/forum/#!searchin/elm-discuss/routing/elm-discuss/WLGZ0a3hOao/uKe_eszKAQAJ

**Comment by megesdal** [comment]
https://github.com/etaque/elm-transit-router

**Comment by wreppun** [comment]
This broad ticket has been covered, well-enough for now, by the integration of elm-transit-router.
